# This is a basic workflow to help you get started with Actions

name: Main workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      # Specify mysql service to run in the container
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: rootsecret
          MYSQL_DATABASE: lms_ljps
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         python -m pip install flask
         python -m pip install flask_cors
         python -m pip install Flask-Testing
         python -m pip install Flask-SQLAlchemy
         python -m pip install mysql-connector-python
         python -m pip install blinker
         pip install flake8

      - name: Verify MySQL connection from host
        run: |
         sudo apt-get install -y mysql-client
         mysql --host 127.0.0.1 --port 3306 -uroot -prootsecret -e "SHOW DATABASES"

      - name: Lint with flake8
        #runs flake8 over the code
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with unittest
        # Set-up database env vars
        env:
          DBNAME: lms_ljps
          DBHOST: 127.0.0.1
          DBUSER: root
          DBPASSWORD: rootsecret
          DBPORT: 3306
        #runs the unittest
        run: |
          python -m unittest UnitTests.py
          python -m unittest IntegrationTests.py
          
      - name: Send email to team if Failure 
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
            # mail server settings
            server_address: smtp.gmail.com
            server_port: 465
            # user credentials
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            # email subject
            subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
            # email body as text
            body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
            # comma-separated string, send email to
            to: jieyin18@gmail.com, ethanlowyc@gmail.com, ooirachel227@gmail.com, limzhiwei03@gmail.com, yimunnnnn@gmail.com 
            # from email name
            from: LJPS-SPM
          

